baseURL = 'carlosmeyer.xyz'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'maverick'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "Über mich"
    url = "/about/"
    weight = 20